CREATE DATABASE urls;

use urls;

CREATE TABLE links (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR (100) NOT NULL,
  alias VARCHAR (30) NOT NULL,
  hitCount INT UNSIGNED,
  secretCode INT UNSIGNED);

